### PR TITLE
Fixes #112 - Calculate vertex normals if not available in the file

### LINKED ISSUE #112: PLY-Reader returns a VertexColorMesh instead of ColorNormalMesh if vertex normals are not written in the file
The PLY-Reader tries first to read a ColorNormalMesh which loads the texture if available. This does not work if the vertex normals are not written in the file (see [PLYMesh.scala:143](https://github.com/unibas-gravis/scalismo-faces/blob/master/src/main/scala/scalismo/faces/io/ply/PLYMesh.scala#L143)). However, the vertex normals can be calculated from the triangle mesh which is already read at that point.

### PR DESCRIPTION
**Pull request by Andreas-Forster**
This pull request tries to read the vertex normals from the file. If they are not present, they are calculated from the already available triangle mesh.

Note: This method will fail if the mesh is not compact, i.e. if there are vertices which are not part of a triangle. However, this would need to be addressed in the vertex normal calculation and not the reader.

### CODE REVIEW

File: src/main/scala/scalismo/faces/io/ply/PLYMesh.scala [hunk 1]
```diff
@@ -140,10 +140,16 @@ object PLYMesh {
...
-    val normals = getSurfaceNormal(vertexProperties, faceProperties, texture, triangles)
 
-    // building the mesh class
-    ColorNormalMesh3D(triangleMesh3D, colors, normals)
+    Try { // use stored vertex normals if available
+      val normals = getSurfaceNormal(vertexProperties, faceProperties, texture, triangles)
+      ColorNormalMesh3D(triangleMesh3D, colors, normals)
+
+    }.getOrElse { // compute the vertex normals using the built mesh - note: this will fail if vertices without adjacent triangles exist
+      val normals = triangleMesh3D.vertexNormals
```
Comment (Ghazi-Bouabene) [inline src/main/scala/scalismo/faces/io/ply/PLYMesh.scala]: For cases that do have "floating" vertices, it might be useful to add a flag to the read method saying "read anyway" .. because in the current case, it will not be possible to read such a mesh until one fixes it with an external tool (removing non-manifold vertices).

Comment (Andreas-Forster) [reply src/main/scala/scalismo/faces/io/ply/PLYMesh.scala]: Internally we rely often on proper meshes. So I think it is not a good idea to offer convenient methods to read meshes which after loading you can for example not render (at least not using vertex normals). In addition, we do not have yet a good set of tools to repair meshes. Which, in my opinion, is also a reason why we should prevent the user to start of working with corrupted meshes.

So when you are really willing to circumvent the safety mechanisms of the conveniece methods for reading a mesh, then you can read the data from a ply file using a snippet like the one that follows and build your mesh out of the parts you have read. In this way you can correct some values before creating the mesh and hence repair it during loading before you use it.

```scala
  val (plyValues, textures) = PlyReader.read("test.ply")
  val (vertexProperties, faceProperties) = PlyMeshReader.getProperties(plyValues)
  val vertices = PlyMeshReader.getVertices(vertexProperties)
  val triangles = PlyMeshReader.getTriangles(faceProperties)
  val triangleMesh3D = TriangleMesh3D(vertices, triangles)
  val colors = PlyMeshReader.getSurfaceColor(vertexProperties, faceProperties, textures, triangles)
```

Comment (Ghazi-Bouabene) [reply src/main/scala/scalismo/faces/io/ply/PLYMesh.scala]: Ok. Other than that am fine to merge.

**Comment by BernhardEgger** [comment]
Thanks for fixing that!

**Review by BernhardEgger — APPROVED** [review]
